---
# https://docs.microsoft.com/en-us/azure/ansible/ansible-overview
# All Azure modules
# https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#azure


# https://www.youtube.com/watch?v=G_gDYlRBAZw
# https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website
# - hosts: localhost
#   vars:
#     resource_group: StaticWebsite
#     storage_account: superfancysitename
#   roles:
#   - azure/storage_account/create
#   - azure/storage_account/status


- hosts: localhost
  vars:
    resource_group: DMR
  roles:
  - azure/app_service/create



# - hosts: localhost
#   tasks:
#   - name: Create storage account
#     azure_rm_storageaccount:
#       resource_group: Testing
#       name: testaccount001
#       account_type: Standard_LRS

  # - name: Create resource group
  #   azure_rm_resourcegroup:
  #     name: "{{ resource_group_webapp }}"
  #     location: "{{ location }}"

  # - name: Create secondary resource group
  #   azure_rm_resourcegroup:
  #     name: "{{ resource_group }}"
  #     location: "{{ location }}"

  # - name: Create App Service Plan
  #   azure_rm_appserviceplan:
  #     resource_group: "{{ resource_group }}"
  #     name: "{{ plan_name }}"
  #     location: "{{ location }}"
  #     is_linux: true
  #     sku: S1
  #     number_of_workers: 1

  # - name: Create App Service on Linux with Java Runtime
  #   azure_rm_webapp:
  #     resource_group: "{{ resource_group_webapp }}"
  #     name: "{{ webapp_name }}"
  #     plan:
  #       resource_group: "{{ resource_group }}"
  #       name: "{{ plan_name }}"
  #       is_linux: true
  #       sku: S1
  #       number_of_workers: 1
  #     app_settings:
  #       testkey: "testvalue"
  #     frameworks:
  #     - name: java
  #       version: 8
  #       settings:
  #         java_container: "Tomcat"
  #         java_container_version: "8.5"

  # - name: Get web app facts
  #   azure_rm_webapp_facts:
  #     resource_group: "{{ resource_group_webapp }}"
  #     name: "{{ webapp_name }}"
  #   register: webapp
    
  # - name: Create Traffic Manager Profile
  #   azure_rm_trafficmanagerprofile:
  #     resource_group: "{{ resource_group_webapp }}"
  #     name: "{{ traffic_manager_profile_name }}"
  #     location: global
  #     routing_method: performance
  #     dns_config:
  #       relative_name: "{{ traffic_manager_profile_name }}"
  #       ttl:  60
  #     monitor_config:
  #       protocol: HTTPS
  #       port: 80
  #       path: '/'

  # - name: Add endpoint to traffic manager profile, using created web site
  #   azure_rm_trafficmanagerendpoint:
  #     resource_group: "{{ resource_group_webapp }}"
  #     profile_name: "{{ traffic_manager_profile_name }}"
  #     name: "{{ traffic_manager_endpoint_name }}"
  #     type: azure_endpoints
  #     location: "{{ location }}"
  #     target_resource_id: "{{ webapp.webapps[0].id }}"
...