---
# -------- Configuration (personal) --------

git_bare_repo: git@github.com:david-rachwalik/pc-setup.git
git_work_repo: ~/pc-setup
git_config: ~/.gitconfig

az_subscriptions: [Pay-As-You-Go]
az_ad_tenant: davidrachwalikoutlook
az_organization: david-rachwalik

az_managed_identities:
- MainDevelopment
# - MainStaging
- MainProduction

az_service_principal: main-sp
az_app_deploy_user: Zevkah

az_devops_service_connections: [DMR-AzureRM]
...